# Generated by Django 5.0.1 on 2024-01-20 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_remove_auction_current_bid_id_auction_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="auction_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.auction",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Auction_Bid",
        ),
    ]
