# Generated by Django 5.0.1 on 2024-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_rename_wathclist_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="current_price",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
