# Generated by Django 5.0.1 on 2024-01-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_rename_host_id_auction_host_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="image",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
    ]
