# Generated by Django 5.0.1 on 2024-01-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_alter_auction_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
