# Generated by Django 5.0.1 on 2024-01-28 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_alter_bid_bid_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="host",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
