# Generated by Django 5.0.1 on 2024-01-28 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_auction_winner_alter_auction_host"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="winner",
        ),
    ]
