# Generated by Django 5.0.2 on 2024-03-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="folowers",
            new_name="followers",
        ),
    ]
