# Generated by Django 5.0.2 on 2024-03-02 16:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_rename_folowers_user_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 2, 16, 32, 34, 780990, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comments",
            name="commented_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commented_post",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
