# Generated by Django 5.0.2 on 2024-03-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_alter_comments_timestamp_alter_posts_timestamp"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
        migrations.RenameModel(
            old_name="Posts",
            new_name="Post",
        ),
    ]
