# Generated by Django 5.0.2 on 2024-03-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_rename_comments_comment_rename_posts_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(max_length=1024),
        ),
    ]
