# Generated by Django 5.0.2 on 2024-03-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_alter_comment_body_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
