# Generated by Django 5.0.2 on 2024-03-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
