# Generated by Django 5.0.2 on 2024-03-02 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_alter_comment_dislikes_alter_comment_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="commented_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commented_post",
                to="network.post",
            ),
        ),
    ]
