# Generated by Django 5.0.2 on 2024-03-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0009_alter_comment_commented_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
    ]
