# Generated by Django 5.0.2 on 2024-03-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0012_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about_me",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
