# Generated by Django 5.0.2 on 2024-03-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0016_remove_comment_likes_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="like_post",
            new_name="liked_post",
        ),
    ]
